#!/usr/bin/env python3
"""
QClaw FinAgent — Notify Agent
Delivers the generated review to configured notification channels.
"""

import asyncio
import json
from datetime import datetime
from typing import Any

import httpx
from loguru import logger
from tenacity import retry, stop_after_attempt, wait_exponential


class NotifyAgent:
    """Agent responsible for delivering review to notification channels."""

    def __init__(self, config: dict):
        self.config = config
        self.name = "NotifyAgent"
        self.enabled = config.get("agents", {}).get("notify", {}).get("enabled", True)
        self.channels = config.get("agents", {}).get("notify", {}).get("channels", [])
        self.max_retries = config.get("agents", {}).get("notify", {}).get("max_retries", 2)
        logger.info(f"[{self.name}] Initialized | Channels: {self.channels}")

    async def execute(self, review: Any) -> dict[str, bool]:
        """
        Execute notification delivery pipeline.

        Args:
            review: Completed DailyReview

        Returns:
            dict: {channel_name: success_bool}
        """
        if not self.enabled:
            logger.warning(f"[{self.name}] Agent disabled, skipping execution")
            return {}

        logger.info(f"[{self.name}] Starting notification delivery for {review.date}")

        results = {}

        for channel in self.channels:
            try:
                if channel == "dingtalk":
                    success = await self._send_dingtalk(review)
                elif channel == "wechat":
                    success = await self._send_wechat(review)
                elif channel == "slack":
                    success = await self._send_slack(review)
                else:
                    logger.warning(f"[{self.name}] Unknown channel: {channel}")
                    continue

                results[channel] = success

            except Exception as e:
                logger.exception(f"[{self.name}] Failed to deliver to {channel}: {e}")
                results[channel] = False

        success_count = sum(1 for v in results.values() if v)
        logger.info(f"[{self.name}] ✅ Delivery complete | {success_count}/{len(results)} successful")

        return results

    def _format_dingtalk_message(self, review: Any) -> dict:
        """Format review as DingTalk Markdown message."""
        # Truncate to DingTalk limit (20000 chars)
        content = review.full_markdown[:19000]

        return {
            "msgtype": "markdown",
            "markdown": {
                "title": f"📊 A-Share Review — {review.date}",
                "text": content,
            },
        }

    def _format_wechat_message(self, review: Any) -> dict:
        """Format review as WeChat Work Markdown message (max 4096 chars)."""
        # WeChat Work markdown is limited, use shorter format
        short_md = f"""📊 A-Share Daily Review | {review.date}

🎭 Sentiment: {review.sentiment_label_cn}

📈 {review.date}
• Limit-Up: {review.key_observations[0]}
• Turnover: See full report

🔥 Key: {', '.join(review.key_observations[:3])}

⚠️ Risk: {review.risk_notes[0] if review.risk_notes else 'None noted'}

[View Full Report](file://{review.output_file})

---
*Generated by QClaw FinAgent*"""

        return {
            "msgtype": "markdown",
            "markdown": {
                "content": short_md[:4000],
            },
        }

    def _format_slack_message(self, review: Any) -> dict:
        """Format review as Slack Block Kit message."""
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"📊 A-Share Review — {review.date}",
                    "emoji": True,
                },
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Sentiment:*\n{review.sentiment_label_cn}"},
                    {"type": "mrkdwn", "text": f"*Theme:*\n{review.key_observations[0]}"},
                ],
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "*⚠️ Risk Notes:*\n" + "\n".join([f"• {n}" for n in review.risk_notes[:2]]),
                },
            },
            {
                "type": "divider",
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f"Generated by QClaw FinAgent | {datetime.now().strftime('%H:%M:%S')}",
                    }
                ],
            },
        ]
        return {"blocks": blocks}

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=1, max=10),
    )
    async def _http_post(self, url: str, payload: dict, timeout: int = 10) -> bool:
        """HTTP POST with retry logic."""
        async with httpx.AsyncClient(timeout=timeout) as client:
            response = await client.post(url, json=payload)
            response.raise_for_status()
            result = response.json()

            # Check for DingTalk/WeChat error codes
            errcode = result.get("errcode", 0)
            if errcode != 0:
                logger.error(f"Webhook error: errcode={errcode}, errmsg={result.get('errmsg', '')}")
                return False

            return True

    async def _send_dingtalk(self, review: Any) -> bool:
        """Send review to DingTalk robot webhook."""
        webhook_url = self.config.get("DINGTALK_WEBHOOK_URL")

        if not webhook_url or "YOUR_TOKEN" in webhook_url:
            logger.warning("[NotifyAgent] DingTalk webhook not configured, skipping")
            return False

        payload = self._format_dingtalk_message(review)
        logger.info(f"[NotifyAgent] Sending to DingTalk webhook...")

        try:
            success = await self._http_post(webhook_url, payload)
            if success:
                logger.info(f"[NotifyAgent] ✅ DingTalk delivery OK")
            return success
        except Exception as e:
            logger.error(f"[NotifyAgent] ❌ DingTalk delivery failed: {e}")
            return False

    async def _send_wechat(self, review: Any) -> bool:
        """Send review to WeChat Work webhook."""
        webhook_url = self.config.get("WECHAT_WEBHOOK_URL")

        if not webhook_url or "YOUR_KEY" in webhook_url:
            logger.warning("[NotifyAgent] WeChat webhook not configured, skipping")
            return False

        payload = self._format_wechat_message(review)
        logger.info(f"[NotifyAgent] Sending to WeChat Work webhook...")

        try:
            success = await self._http_post(webhook_url, payload)
            if success:
                logger.info(f"[NotifyAgent] ✅ WeChat delivery OK")
            return success
        except Exception as e:
            logger.error(f"[NotifyAgent] ❌ WeChat delivery failed: {e}")
            return False

    async def _send_slack(self, review: Any) -> bool:
        """Send review to Slack webhook."""
        webhook_url = self.config.get("SLACK_WEBHOOK_URL")

        if not webhook_url or "YOUR_WEBHOOK" in webhook_url:
            logger.warning("[NotifyAgent] Slack webhook not configured, skipping")
            return False

        payload = self._format_slack_message(review)
        logger.info(f"[NotifyAgent] Sending to Slack webhook...")

        try:
            success = await self._http_post(webhook_url, payload)
            if success:
                logger.info(f"[NotifyAgent] ✅ Slack delivery OK")
            return success
        except Exception as e:
            logger.error(f"[NotifyAgent] ❌ Slack delivery failed: {e}")
            return False


# ─── Standalone Test ───────────────────────────────────────────
if __name__ == "__main__":
    import json

    async def test():
        from agents.review_agent import DailyReview

        config = {
            "agents": {"notify": {"enabled": True, "channels": ["dingtalk"]}},
            "DINGTALK_WEBHOOK_URL": "https://oapi.dingtalk.com/robot/send?access_token=test",
        }
        agent = NotifyAgent(config)

        review = DailyReview(
            date="2026-05-14",
            sentiment_label="greed",
            sentiment_label_cn="贪婪",
            market_snapshot_md="## 📈 Market Snapshot\n- Test data",
            theme_heatmap_md="## 🔥 Theme Heatmap",
            key_observations=["AI sector leads momentum"],
            risk_notes=["High-board divergence risk"],
            forward_outlook="Monitor AI sector tomorrow",
            full_markdown="# Test Review\nFull markdown content",
            output_file="output/test.md",
            timestamp="2026-05-14T15:30:00",
        )

        results = await agent.execute(review)
        print(json.dumps(results, indent=2))

    asyncio.run(test())